name: ELK Stack CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Compose
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install docker-compose
    
    - name: Check Docker and Docker Compose versions
      run: |
        docker --version
        docker-compose --version
    
    - name: Create necessary directories
      run: |
        mkdir -p data/elasticsearch
        chmod 777 data/elasticsearch
    
    - name: Pull Docker images
      run: docker-compose pull
    
    - name: Start ELK Stack
      run: docker-compose up -d
    
    - name: Wait for services to be ready
      run: |
        sleep 60
        docker-compose ps
    
    - name: Check Elasticsearch health
      run: |
        docker-compose exec -T elasticsearch curl -f http://localhost:9200/_cluster/health?wait_for_status=green&timeout=50s
    
    - name: Check Kibana is running
      run: |
        docker-compose exec -T kibana curl -f http://localhost:5601/api/status
    
    - name: Check Logstash is running
      run: |
        docker ps | grep logstash
    
    - name: Check Filebeat is running
      run: |
        docker ps | grep filebeat
    
    - name: Show Docker logs on failure
      if: failure()
      run: |
        docker-compose logs elasticsearch
        docker-compose logs kibana
        docker-compose logs logstash
        docker-compose logs filebeat
    
    - name: Stop ELK Stack
      run: docker-compose down
